export const queryPage =
`*[ page_slug.current == $slug ][0]{
  meta_description,
  share_image{
    _type,
    asset->{
      url,
      _type,
      altText,
      description,
      title,
      metadata{
        dimensions{
          height,
          width
        }
      }
    }
  },
  page_slug,
  page_title,
  hero,
  sections[]{
    _type == "imageBlock" => {
      _key,
      _type,
      block_image{
        _type,
        asset->{
          url,
          _type,
          altText,
          description,
          title,
          metadata{
            dimensions{
              height,
              width
            }
          }
        }
      },
      layered_image,
      image_layers[]{
        _key,
        _type,
        asset->{
          _ref,
          _type,
          url,
          altText,
          description,
          title,
          metadata{
            dimensions{
              height,
              width
            }
          }
        }
      }
    },
    _type == "imageGrid" => {
      _key,
      _type,
      grid_copy,
      grid_title,
      image_grid,
    },
    _type != "imageBlock" && _type != "imageGrid" => {
      _key,
      _type,
      block_copy,
      block_title,
      block_image{
        _type,
        asset->{
          url,
          _type,
          altText,
          description,
          title,
          metadata{
            dimensions{
              height,
              width
            }
          }
        }
      },
      layered_image,
      image_layers[]{
        _key,
        _type,
        asset->{
          _ref,
          _type,
          url,
          altText,
          description,
          title,
          metadata{
            dimensions{
              height,
              width
            }
          }
        }
      },
      cta,
      has_cta,
      has_image
    }
  }
}`

export const queryHeader =
`*[_type == "header"][0]{
  home_link,
  nav_links,
}`

export const queryFooter =
`*[_type == "footer"][0]{
  copyright_text,
}`